import "~/styles/globals.css";

import { UserProvider } from '@auth0/nextjs-auth0/client'

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config, library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';

import Layout from '../components/Layout';

config.autoAddCss = false;
library.add(fas);

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Layout>
            {children}
          </Layout>
        </UserProvider>
      </body>
    </html>
  );
}
